[build]
  command = "yarn install && yarn prisma:generate && yarn migrate"
  functions = "functions"
  publish = "functions"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

