# This is a comment in netlify.toml
[build]
  # command = "yarn install && yarn prisma:generate && yarn migrate"
  # command = "yarn && yarn prisma:generate && yarn prisma migrate deploy"
  command = "yarn && yarn prisma migrate resolve --rolled-back 20240414065451_migration2_14_april_5 && yarn prisma:generate && yarn prisma migrate deploy"
  functions = "functions"
  publish = "functions"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    
  